"""empty message

Revision ID: 1f4d3ce24d13
Revises: 
Create Date: 2017-01-12 13:41:07.691258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4d3ce24d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('responses')
    op.drop_table('requests')
    op.drop_table('dates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_1', sa.INTEGER(), nullable=True),
    sa.Column('user_2', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_name', sa.VARCHAR(), nullable=True),
    sa.Column('restaurant_address', sa.VARCHAR(), nullable=True),
    sa.Column('restaurant_picture', sa.VARCHAR(), nullable=True),
    sa.Column('meal_time', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('meal_type', sa.VARCHAR(), nullable=True),
    sa.Column('location_string', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.NUMERIC(), nullable=True),
    sa.Column('longitude', sa.NUMERIC(), nullable=True),
    sa.Column('meal_time', sa.VARCHAR(), nullable=True),
    sa.Column('filled', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('filled IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_proposed_to', sa.INTEGER(), nullable=True),
    sa.Column('user_proposed_from', sa.INTEGER(), nullable=True),
    sa.Column('request_id', sa.INTEGER(), nullable=True),
    sa.Column('filled', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('filled IN (0, 1)'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
