"""parent table removed

Revision ID: a7bf8d2a7284
Revises: c9b7350a390c
Create Date: 2017-01-23 13:56:33.700815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bf8d2a7284'
down_revision = 'c9b7350a390c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
