"""rename proposals

Revision ID: c9b7350a390c
Revises: 
Create Date: 2017-01-20 13:27:34.610046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b7350a390c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_proposed_to', sa.Integer(), nullable=True),
    sa.Column('user_proposed_from', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('filled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_proposed_to', sa.INTEGER(), nullable=True),
    sa.Column('user_proposed_from', sa.INTEGER(), nullable=True),
    sa.Column('request_id', sa.INTEGER(), nullable=True),
    sa.Column('filled', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('filled IN (0, 1)'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('proposals')
    # ### end Alembic commands ###
